services:
  db:
    image: postgres:latest
    ports:
      - 5432:5432
    container_name: trello_clone_db
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=trello-clone
    volumes:
      - db_data:/var/lib/postgressql/data

volumes:
  db_data: